/**
 * Launch Cohort Allowlist
 *
 * Controls which offer pages are publicly accessible during phased rollout.
 * When LAUNCH_MODE is enabled, only slugs in LAUNCH_COHORT_SLUGS will render.
 * All other slugs return real 404s (not noindex, not redirects).
 *
 * Usage:
 * - Set NEXT_PUBLIC_LAUNCH_MODE=cohort in .env to enable gating
 * - Add slugs to LAUNCH_COHORT_SLUGS set below
 * - Use isOfferLaunchEligible(slug) to check eligibility
 */

/**
 * When true, only offers in LAUNCH_COHORT_SLUGS are accessible.
 * When false (default), all offers behave normally.
 */
export const LAUNCH_MODE = process.env.NEXT_PUBLIC_LAUNCH_MODE === 'cohort';

/**
 * Set of slugs that are eligible to be shown during launch.
 * These should be high-quality offers with real promo codes.
 *
 * Target: ~200 offers for initial launch cohort.
 */
// COHORT_START
export const LAUNCH_COHORT_SLUGS = new Set<string>([
  // === CURATED LAUNCH COHORT (117 slugs) - Top Whop Affiliates ===
  // Source: data/launch-cohort-curated-101.json + top-100-rewritten-content.json (first 20)
  // Applied: 2025-12-16, Updated: 2026-01-08
  '-silver-tier-fyndit',
  '4orte-tiktok-upgrade',
  'ace-of-trades-',
  'ai-news-bot',
  'alertsify',
  'american-dream-mentorship',
  'amnotify-japan-renewal',
  'anonymous-sport-bets',
  'ascent-repricer',
  'beat-the-books',
  'bet-bettor-weekly',
  'betmagic-pro-membership',
  'blastoises-premium',
  'boka-trading-premium',
  'boosted-betz-premium',
  'bullish-bandits',
  'chart-hackers-pay-with-crypto',
  'chroma-trading',
  'coliseeprivateclub-premium',
  'creator-cartel',
  'crypto-archie-vip',
  'datawise-sports-betting',
  'deal-soldier',
  'divine-premium-access',
  'doc-prop-gold',
  'dodgys-dungeon',
  'ecom-tools-pro',
  'edu-elite-30-platinum',
  'elevate-community',
  'empire-sports',
  'enrich-trades-blueprint',
  'flash-fund-premium',
  'flipalert-membership-usa',
  'freecash-premium',
  'frugal-season',
  'full-port-university-annual',
  'gg33-enlightened-academy',
  'glo-sports-chat',
  'goat-sports-bets-membership',
  'grindlife-plays',
  'heatseeker-access',
  'hidden-society-trading',
  'hobbyist-collective-membership',
  'hold-my-hand-wholesale-pass',
  'house-of-resell',
  'house-of-stimms-vip',
  'jdub-trades-premium',
  'larrys-lounge-premium',
  'limitless-rei-wholesale',
  'lowkey-discord-membership',
  'lunch-money-membership',
  'market-fluidity-university',
  'mc-sports-premium',
  'media-metas',
  'meme-mafia',
  'miles-high-club-crypto-pay',
  'mogul-stock-group-premium',
  'momentum-monthly',
  'moon-trades-lifetime',
  'ndotdiab-vip-access',
  'new-age-trading-premium',
  'nextwave-indicators',
  'ofm-empire-vip-full-access',
  'owls-full-access',
  'parlay-minds-premium',
  'parlayscience-discord-access',
  'peloswing-premium-access',
  'pj-trades-premium',
  'pokefinder',
  'polar-chefs-premium',
  'potion-discord-access-crypto',
  'potion-tracker-whale',
  'profit-pioneers',
  'propbet-mafia',
  'propfellas-vip',
  'resale-radar-discord',
  'resellers-paradise-premium',
  'scalboost-club',
  'scarface-trades-premium',
  'sharpmoney-all-access-vip',
  'shocked-crypto-payments',
  'skyridge-toolbox',
  'sourced-betting-bots',
  'stellar-aio',
  'stock-talk-insiders',
  'tailored-trades-premium',
  'the-haven',
  'the-options-cartel-full-access',
  'the-sweepers-vip',
  'the-yard-dropship-mastermind',
  'ticket-broker-u-pro',
  'titans-algo-pro',
  'tms-1-on-whop',
  'tms-heavy-hitters-',
  'trade-with-insight-pro',
  'unity-academy-membership',
  'vulture',
  'wealth-group-crypto-pay',
  'your-first-dollar',
  'zth-player-accelerator',
  'zzz-money-club-vip',
  // === EXPANDED BATCH (45 slugs) - High-Value Rewritten Content ===
  // Updated: 2026-01-13
  // Note: 5 slugs deleted from Whop (korvato-gold-rush, metatradingai, alliance-group-coaching, growthopia-fz-llc, liv-cam-paid)
  'airbnb-empire-builder',
  'm1-capital-accelerator',
  'the-8-figure-masterclass',
  'daniel-g-hubzome-lda-speaking',
  'minotaur-consulting-services',
  'omnifunds',
  'million-dollar-brand-club',
  'global-wealth-mentorship',
  'asgard-bootcamp',
  'youtube-consulting',
  'lifetime-diamond-package-',
  '200k-500k-challenge',
  'lux-nomads-essentials',
  'innova-trade-ai',
  'devvy',
  // === NEW ADDITIONS (30 slugs) - 2026-01-13 ===
  'sober-living-riches',
  'optinsio',
  'fes-bootcamp',
  'the-only-system-you-need',
  'jlu-637',
  'platinum-tier-fast-action',
  'real-business-solutions',
  'royalty-hero-elite',
  'elite-coaching-academy',
  'arbitrage-society',
  'ttw-inner-circle',
  'daniel-g-x-d2d-con',
  'daniel-g-x-alkaline-electric',
  'capital-funding-accelerator',
  'skillset-solutions',
  'springboard-to-wealth',
  'riverz-marketing',
  'wall-street-academy',
  'leadconsulting-ai',
  'tms-spartan-ai-bot',
  'great-energy-capital',
  'just-funded',
  'acquisition-network-',
  'agency-partner-package',
  'wholesale-to-millions',
  'the-trading-apprentice',
  'career-evolved',
  'lux-nomads-vip',
  // === EDITORIAL REVIEWS BATCH (42 slugs) - 2026-01-16 ===
  'the-godspeed-growth-system',
  'section-8-cartel',
  'affiniti-flow',
  'swayer',
  'listing-agent-accelerator',
  'airflow',
  'sovereign-man',
  'momentum-circle',
  'fernpicks-diamond-package',
  'qa-automation-job-interviews',
  'tech-sales-job-interviews',
  'osa-gold-program',
  'the-ai-incubator',
  'acquisition-ace',
  'learn-minerals',
  'locatelli-acquisition',
  'data-engineer-academy-fin',
  'baller-package',
  'the-high-ticket-ecom-program',
  'electrin-group',
  'consulting-utopia-dfy',
  'fit-n-healthy',
  'ai-profit-lab',
  'formula-6',
  'ayecon-academy-lifetime-membership',
  'mdbc-tiktok-hop',
  'amazon-inner-circle',
  'the-real-sales-academy',
  'digital-creator-university',
  'gold-tier',
  'exclusive-calls',
  'beyond-clinical-care',
  'info-scaler',
  'diagofit',
  'goodlife-brand-accelerator',
  'accelerator-program',
  'inovate',
  'learn-airbnb-arbitrage',
  'sickboytrades-mentorship',
  'the-black-room',
  'tiktok-shop-accelerator',
  '7th-level-community',
  // === EDITORIAL REVIEWS BATCH 2 (67 slugs) - 2026-01-19 ===
  '1-on-1-coaching',
  '1of1locks',
  '360-sales-agency',
  '4everpaidbets',
  'accs-bot-vinted',
  'ai-for-pros',
  'aj-trading',
  'alex-crypto-universe',
  'alminmilanovic',
  'amazon-aco',
  'betwithhaddy',
  'bullprooftrading-strategy',
  'bullstocks',
  'businessgrowr-aaf-dfy-setup',
  'capital-44-elite-group',
  'cc-compass',
  'cdr-premium-betting',
  'chaos-indicator-for-trading',
  'cisero-ai',
  'coaching-by-brian',
  'creativeforge',
  'credit-repair-balance-2nd-pay',
  'criscklukks-whop',
  'dcoptions',
  'ddu-online-services-agency-4',
  'degen-vip',
  'delux',
  'dialos-major-league-profits',
  'diontrades',
  'dm-setting',
  'domsprops',
  'dubai-plug',
  'earnit-media',
  'essentials-to-trading',
  'falco-queue-buster',
  'flipflip-membership-og',
  'flipseek',
  'flxpickz-premium',
  'forked-creatives',
  'founders-arm',
  'freedom-team-mentorship',
  'freedomers',
  'future-founders-club',
  'game-changer-premium',
  'ghost-inner-circle',
  'glitchybets',
  'high-ticket-incubator',
  'hooksquare-contractors',
  'iced-investments-subscription',
  'infoprosio',
  'institutional-trading',
  'intensevalue',
  'inventory-insiders',
  'jlgrowth',
  'juiced-bets-vip-discord',
  'locks-together-premium',
  'master-your-money',
  'opusmagna-trading',
  'resistance',
  'saas-university',
  'steal-my-agency',
  'tennisxpert-premium',
  'the-locksmiths-hq',
  'traders-accelerator',
  'uncle-shaundys-trading-den',
  'zeus-bets',
  'zoom-trading-vip',
  // === EDITORIAL REVIEWS BATCH 3 (9 slugs) - 2026-01-22 ===
  'resell-radar',
  'tradialy',
  'pikes-peak-trades-advantage',
  'wave-maestro',
  'remote-riches',
  'opc-all-plays',
  'sigmavue',
  'exotic-fleet-formula',
  'canary-chain',
  // === PROMO CODE BATCH 1 (100 slugs) - 2026-01-29 ===
  'speed-ramp-from-a-to-z',
  '1-month-premium',
  '1-of-1-traders-full-access',
  '1-month-access-vipparlay-king',
  '1-on-1-mentorship-lifetime',
  '100-creative',
  '10kto50k-challenge-elite-plan',
  '1',
  '3-days-free-luxury-picks',
  '3-leaf-clover',
  '333picks',
  '3m-trading-vip-group-access',
  '4-leaf-clover',
  '6-figure-wash-system',
  '60-day-ab-strength-for-golfers',
  'itsbucketsnba-vip-telegram',
  'a-z-trading-guide-',
  'aa-trading',
  'ad-plus',
  'adt-diamond-lifetime',
  'adt-vip-gold-complete',
  'aementorship-basic-mentorship',
  'ai-fusion-megapack',
  'ai-signals-premium',
  'alive-trades-alliance-ata',
  'am-elites-premium',
  'amzshifu-university',
  'ape-trading',
  'apex-fitness-and-mind-mastery',
  'ar-trades',
  'archetype-premium',
  'atm-picks-pass',
  'abhey-takes-down-vegas-free',
  'acesso-alpha',
  'advanced-english-community',
  'agency-blueprint',
  'agency-domain',
  'algo28-day-trading-signals',
  'algobot-premium',
  'algorithmic-trading-blueprint',
  'all-access',
  'all-access-vip',
  'all-in-one-indicator-package',
  'alpha-market-pro',
  'amazon-fba-mastery',
  'amazon-fba-success-network',
  'american-dream-trading-crypto',
  'american-dream-trading-futures',
  'american-dream-trading-premium',
  'angelo-props-bread-winners',
  'anonymous-traders',
  'arbitrage-alley-pro',
  'ashleydoubles-community',
  'attention-economy-club',
  'aura-picks-vip',
  'aura-picks-vip-pass',
  'ayecon-academy-monthly-mentorship',
  'bankroll-bros-weekly',
  'bfx-signals',
  'blw-master-app',
  'ballerpicks-vip',
  'baseline-bets',
  'basic-plan',
  'basic-trading-mentorship',
  'beamly-hyper-growth',
  'best-of-both-worlds',
  'bet-sports-daily',
  'betdubs-premium',
  'betropolis-vip-esports-bot',
  'betting-central-101',
  'bettorprocess-member',
  'big-tick-energy-premium',
  'bigjoebets',
  'bigplaynate-monthly-gl',
  'blackhawk-indicator',
  'blackwolftrading',
  'blastoises-lifetime-premium',
  'blitzersports-vip',
  'blockchain-bureau-apprentice',
  'bobbys-bets-sports-analytics',
  'bookie-breakers-vip',
  'boominati-io-membership',
  'bors-trading-premium',
  'brand-leverage-blueprint',
  'brand-partnership-blueprint',
  'braver-crypto-vip',
  'bronze-package',
  'build-your-brand-ecom-coaching',
  'build-your-first-app-with-ai',
  'bulhaven-trading-group',
  'bullfrogs-investment-community',
  'caa-itin-forensic-training',
  'ccs-collectibles',
  'ceo-trades-lifetime-access',
  'clean-sweeps-vip',
  'cms-basic-ta-course',
  'cms-vip',
  'cryptowzrd',
  'cali-betz',
  'caps-7-day-package',
]);
// COHORT_END

/**
 * Check if an offer slug is eligible to be shown.
 *
 * @param slug - The offer slug to check (should be lowercase/canonical)
 * @returns true if offer should be rendered, false if it should 404
 */
export function isOfferLaunchEligible(slug: string): boolean {
  // When launch mode is off, everything is eligible (normal behavior)
  if (!LAUNCH_MODE) return true;

  // When launch mode is on, only cohort slugs are eligible
  return LAUNCH_COHORT_SLUGS.has(slug.toLowerCase());
}

/**
 * Get the count of offers in the launch cohort.
 * Useful for logging/debugging.
 */
export function getLaunchCohortCount(): number {
  return LAUNCH_COHORT_SLUGS.size;
}

/**
 * Check if launch mode is currently active.
 * Useful for conditional logic in components.
 */
export function isLaunchModeActive(): boolean {
  return LAUNCH_MODE;
}
